# Generated by Django 5.0.1 on 2024-01-31 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_qtd_total'),
        ('produto', '0005_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_promocional',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao_id',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.variacao'),
        ),
    ]
